### ISSUE TITLE
Export / Import

### ISSUE THREAD

**Issue by nate-gray** [nate-gray/KiL#10]

**Comment by Waterski24** [comment]
It would be cool, too, if the database exported itself on exit and imported itself on launch

**Comment by nate-gray** [comment]
@Waterski24  In order to do that, the file would need to be saved and exist in the same location every time.  So we would need to write it to some hidden location, which could be difficult to handle depending on the platform being used.  I agree it would be nice - maybe a feature we can add if we have time?
