### ISSUE TITLE
Handle these scenarios for adding a new line item

### ISSUE THREAD

**Issue by nate-gray** [nate-gray/KiL#48]
An item should not be added and an error should be displayed in these cases. 

- No name entered for the item. 
- No value entered for the current stock. 
- Non-int value entered for current stock. 
- Current stock exceeds 999. 
- Name exceeds 20 alphanumeric characters. 
- Name contains non-alphanumeric characters.

**Comment by nate-gray** [comment]
Linked issue: https://github.com/ngray311/KiL/issues/18

**Comment by JRHummel** [comment]
Is there a reason to limit stock values and max name characters besides that we made it a requirement?

**Comment by nate-gray** [comment]
This is strictly based off the requirements.  I think part of the reason we added that requirement was that so we had something to shoot for.  I am sure we could find a max value for each of them that would start breaking things, but definitely not a major issue. 

So I guess it just depends on how strict we want to be with our original requirements.

**Comment by Waterski24** [comment]
handled in my latest pull request

**Comment by nate-gray** [comment]
Looks good.
